### ISSUE TITLE
"Your shows" tab still showing on home page

### ISSUE THREAD

**Issue by Maarten-DLVW** [theRealPadster/spicetify-hide-podcasts#111]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.25.1011.g0348b2ea
- Spicetify version: 2.28.0
```

### 📝 Description

When opening spotify, the "Your Shows" tab is still there, but when i click to open it (or open anything else for that matter) and come back to the homepage, it's gone like it should be.

**Comment by theRealPadster** [comment]
@Maarten-DLVW Could you try the latest version? This should be fixed now, please let me know.

**Comment by Maarten-DLVW** [comment]
yes it's fixed now :)
