### ISSUE TITLE
Episodes For You still recommending Podcasts

### ISSUE THREAD

**Issue by BeverlyLaurelBLVD** [theRealPadster/spicetify-hide-podcasts#114]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for macOS (Apple Silicon)
1.2.26.1187.g36b715a1
Spicetify v2.28.1
Theme: Nord / Spotify
Extensions: djinfo.js, seekSong.js, playNextWrapper.js, made-for-you-shortcut.js, imageOpener.js, songstats.js, copytoclipboard.js, volume-profiles.js, group-session.js, QueueTime.js, fullAlbumDate.js, hidePodcasts.js, CoverAmbience.js, wikify.js, autoSkipWrapper.js, spotifyBackup.js, playlist-icons.js, quickQueue.js, imaged-folders.js, find-duplicates.js, genre.js, spotispy.js, upcomingSong.js, section-marker.js, skip-song-part.js, theme.js
Custom apps: marketplace, stats, eternal-jukebox, better-local-files, combined-playlists
```

### 📝 Description

As title describes. 

Out of the podcasts shown, I'm only following 4 of them: The Todd V Show, Eric AbroadCast, Austen Summers Podcast, In Moderation

### 📸 Screenshots

<img width="1092" alt="Screenshot 2023-12-16 at 12 50 59 PM" src="https://github.com/theRealPadster/spicetify-hide-podcasts/assets/100189818/1f606353-3f2d-46c5-8e7a-eee1377f762c">

**Comment by theRealPadster** [comment]
I've just published an updated version (2.8.0). Could you update and try it now? If you're using Marketplace, you will need to reload/restart Spotify.

**Comment by theRealPadster** [comment]
And I'd also just like to confirm that you have the extension enabled?
<img width="394" alt="image" src="https://github.com/theRealPadster/spicetify-hide-podcasts/assets/1565883/475dff09-5829-498a-bfe3-08b825de71df">

**Comment by theRealPadster** [comment]
Can you download and try the new version 3.0 that I just released? It should make things much much more reliable.

**Comment by theRealPadster** [comment]
Issue should be fixed. Closing due to lack of response.
