### ISSUE TITLE
Podcasts still showing on homepage

### ISSUE THREAD

**Issue by Maarten-DLVW** [theRealPadster/spicetify-hide-podcasts#121]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.26.1187.g36b715a1
Spicetify v2.30.0
windows 10
```

### 📝 Description

The "your shows" tab still shows on my homepage

**Comment by theRealPadster** [comment]
Did you try the agressive mode?

**Comment by theRealPadster** [comment]
Can you download and try the new version 3.0 that I just released? It should make things much much more reliable.

**Comment by theRealPadster** [comment]
Closing as fixed.
