### ISSUE TITLE
Podcast still showing up

### ISSUE THREAD

**Issue by fortgoodnite** [theRealPadster/spicetify-hide-podcasts#122]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.26.1187.g36b715a1
Spicetify v2.30.0
Windows 11
```

### 📝 Description

Your shows tab wont leave

**Comment by theRealPadster** [comment]
Did you try aggressive mode?

**Comment by theRealPadster** [comment]
Can you download and try the new version 3.0 that I just released? It should make things much much more reliable.

**Comment by fortgoodnite** [comment]
> Can you download and try the new version 3.0 that I just released? It should make things much much more reliable.

its still there even after removing and re-adding it, yes i do have aggressive mode on

**Comment by fortgoodnite** [comment]
i meant installing through the marketplace sorry but ill try that now and see if it works

**Comment by theRealPadster** [comment]
@fortgoodnite any update?

**Comment by theRealPadster** [comment]
Closing as fixed.
