### ISSUE TITLE
cant find the toggle

### ISSUE THREAD

**Issue by pWoLiAn** [theRealPadster/spicetify-hide-podcasts#13]
![image](https://user-images.githubusercontent.com/49567139/119459801-a9994580-bd5b-11eb-9a08-f4b9dfe1b13b.png)
Spotify version 1.1.4.197.g92d52c4f

**Comment by theRealPadster** [comment]
Looks like you are using the legacy Spotify. Are you also using the legacy Spicetify (pre version 2.0)? 
Can you download the latest release from [here](https://github.com/theRealPadster/spicetify-hide-podcasts/releases/tag/v1.0.0) and make sure everything is installed properly, and run `spicetify apply` again?

**Comment by pWoLiAn** [comment]
The legacy version seems to be working.Thx for the quick fix :D
