### ISSUE TITLE
Podcast related items sometimes load in after page load

### ISSUE THREAD

**Issue by lazyb5** [theRealPadster/spicetify-hide-podcasts#17]
Using 1.1.61.583.gad060c66-a 

Podcast related items show on top of my main screen. They will hide with a toggle of "hide podcasts" button. But then new ones show again.

**Comment by theRealPadster** [comment]
What items are showing up? Are you able to post a screenshot? 
Also, can you outline the steps to reproduce a little better? You have the extension enabled (podcasts disabled) before you start Spotify, then you launch it and they show up. And if you turn off the extension and turn it back on, they disappear. And which new ones show again, when?

**Comment by lazyb5** [comment]
![pcast](https://user-images.githubusercontent.com/23584680/121608001-10d31d00-ca1f-11eb-928e-36ea9b516ddc.PNG)

It will then disappear when I toggle hide podcasts on and off. Nothing is showing now, but I will capture video of it next time Something shows up. I have hide podcast turned on when Spotify is started. I'll see if they show up with Spotify just running or show up on restart.

**Comment by lazyb5** [comment]
https://user-images.githubusercontent.com/23584680/121634415-81476180-ca52-11eb-9f66-0613c876e1be.mp4

**Comment by theRealPadster** [comment]
Thanks for the screen+video. When you start Spotify with the extension enabled, does it show podcasts right away, or just after using the app for a while? Are you staying on the home screen or navigation around the app? I have pushed an update (8f4ca3d) that should help if podcasts are showing up on initial app load, can you give that a try and see if it makes any difference?

**Comment by lazyb5** [comment]
I will update this post with me data as I see ads. One popped UP after app was just idle for about 15 hours. I was navigating into the home page from another playlist.

**Comment by lazyb5** [comment]
![image](https://user-images.githubusercontent.com/23584680/122564966-f3e8ac00-d013-11eb-93f4-d5b70018703d.png)

Had computer sitting idle. Stayed on the front page of Spotify. Appeared During the idle.

**Comment by theRealPadster** [comment]
I tried leaving it open overnight on the homepage and it still didn't have any podcast items appear. I'm not sure how I'd test or fix it. Right now it listens and scans on app history/path name changes. If you open up the dev console, does it show anything like this after it shows podcast stuff? 
![image](https://user-images.githubusercontent.com/1565883/122651959-0e04b600-d10a-11eb-95bb-cb1c89b78828.png)

**Comment by theRealPadster** [comment]
I added a "debug" branch that has a little more logging enabled. Could you switch to that in case it helps me figure out what's going on? If the content of the page is refreshing somehow without actually triggering a pathname change, I'm not sure there's much I can do. I don't want to leave MutationObserver that waits for the page to be ready running all the time, as it would kill performance and trigger it to re-run way too often.

**Comment by lazyb5** [comment]
I don't know how to get to dev console, I'm a n00b. I have installed the dev branch. Likewise, I also don't know how to get the log you're looking for with that.

**Comment by theRealPadster** [comment]
Run `spicetify enable-devtool` and then it should have a "develop" section in the Spotify menu. Open the web inspector/console in that menu. It should open a window with a bunch of logs at the bottom. I think that's all you need to do to set it up, but I'm on my phone, so lmk if that doesn't do it.

**Comment by lazyb5** [comment]
So a podcast carousel did show up at idle. There wasn't much in the log, don't know if I'm not looking in the right place. THE End is the entry of me clicking hide podcasts two times to restart it. Seems like it just not reacting at all. Are there other issues at play with my spictify install?
![image](https://user-images.githubusercontent.com/23584680/122672958-42c14d80-d19c-11eb-8430-a2aa1fc9ee4e.png)

**Comment by theRealPadster** [comment]
It just happened to me as well. I just open the app and was playing music from the homepage. The logs don't show any load events or anything either, so it must be refreshing the content without doing any navigation. I'll have to see if it's possible to catch when that happens without tanking performance... :/
![image](https://user-images.githubusercontent.com/1565883/122802702-a9756280-d293-11eb-986f-69a1f4e4222c.png)

**Comment by theRealPadster** [comment]
Just adding a note here so I don't forget - khanhas suggested  
> You can always use MutatationObserver and setTimeout to wait till app is "fully" loaded.

This is an alternative to the method of waiting for content, but it's debatable if it's any better than specifically hardcoding which item to wait for if the main item doesn't work (e.g. Search page). 

It doesn't look like there's a good way to tell if new content has loaded in. I can maybe experiment with leaving the MutationObserver running, but we may just have to live with it :/

**Comment by theRealPadster** [comment]
@lazyb5 It does look like you could potentially use the "home config" feature from [Spicetify v2.3.0](https://github.com/khanhas/spicetify-cli/releases/tag/v2.3.0) as a workaround

**Comment by theRealPadster** [comment]
@mix3d what are the "advanced options"? This extension just has enabled or disabled.

**Comment by mix3d** [comment]
@theRealPadster 
![image](https://user-images.githubusercontent.com/1474137/142024315-fc39750c-fd72-4bd5-861f-29b028148da5.png)
The setting to turn on/off

**Comment by mix3d** [comment]
the classnames seem to be obfuscated now: 
![image](https://user-images.githubusercontent.com/1474137/142026449-918b73b3-4159-4862-b324-f83f189855a7.png)

**Comment by mix3d** [comment]
Aha! I thought I had updated my spicetify with `spicetify update`, but the correct command was `spicetify upgrade`. Moving from v2.7.1 to v2.8.1 fixed my issues. Hooray!

**Comment by theRealPadster** [comment]
@lazyb5 I just added an "aggressive mode" option that you can enable. Could you update to 2.4.0 and see if it helps?

**Comment by lazyb5** [comment]
> 

OK, I have it enabled. Some podcasts have been showing up, but not a lot.  I'll let you know if any show up in this mode.

**Comment by theRealPadster** [comment]
Closing as resolved for now. Feel free to re-open if the issue persists.
