### ISSUE TITLE
No "hide podcasts" button

### ISSUE THREAD

**Issue by yp261** [theRealPadster/spicetify-hide-podcasts#20]
Hi, don't know how much of a description I can do regarding this thing. There is no button to hide podcasts
OS: Windows 10
Spotify isn't installed from Windows Store. Spicefy and spotify updated to the latest versions

![image](https://user-images.githubusercontent.com/16986482/130986583-0fe9936e-a364-4a8c-a4e2-7f6465cf5e8c.png)

![image](https://user-images.githubusercontent.com/16986482/130986736-d5a9e610-8959-44ad-bd13-c2ddbfaa6516.png)

**Comment by theRealPadster** [comment]
Hey @yp261 @TerraDK Can you update to spicetify 2.6.3 and try it? It seems to have fixed the broken hook :)

**Comment by TerraDK** [comment]
> Hey @yp261 @TerraDK Can you update to spicetify 2.6.3 and try it? It seems to have fixed the broken hook :)

Its working properly now, thank you!

**Comment by theRealPadster** [comment]
Glad to hear it!
