### ISSUE TITLE
Where can I find this theme? 

### ISSUE THREAD

**Issue by milindgoel15** [theRealPadster/spicetify-hide-podcasts#21]
![image](https://user-images.githubusercontent.com/45682747/131119227-2dbfed54-6f8b-4028-a888-1ec85b94e089.png)
Taken from here :-
https://github.com/3raxton/spicetify-custom-apps-and-extensions/tree/main/spicetify-hide-podcasts#usage

**Comment by theRealPadster** [comment]
That's the purple colour scheme for the default spicetify theme.
