### ISSUE TITLE
"Hide podcasts" button not showing up

### ISSUE THREAD

**Issue by djpowers** [theRealPadster/spicetify-hide-podcasts#22]
**Describe the bug**
The menu option to hide podcasts is not appearing.

**To Reproduce**
1. Download `hidePodcasts.js` and move to `~/.config/spicetify/Extensions`
2. Run the spicetify commands to install.

**Expected behavior**
Menu option to hide podcasts would be displayed.

**Screenshots**
<img width="213" alt="image" src="https://user-images.githubusercontent.com/4978418/145725353-ada227ae-9d7e-4207-b3e0-d39c0eae011d.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.6.1
 - Spotify version: 1.1.74.631.g0b24d9ad
 - Spicetify version: 2.8.3
 - Extension version: 2.1.0

**Additional context**
I saw that this issue has occurred before, most recently reported in #20. Not sure if something may have broken again due to Spotify updates. Of note, the default Spicetify extensions are able to be loaded.

**Comment by theRealPadster** [comment]
Can you run this in the dev tools? I'm guessing Spotify just updated and the platform hook is broken. 
```js
new Spicetify.Platform.Menu.Item('Test button', false, (self) => {
        console.log("test");
    }).register();
```

**Comment by djpowers** [comment]
Thanks for the reply, I ran the above in the dev tools and it didn't throw an error, but it did not appear to log the test message or add a new menu item.

**Comment by theRealPadster** [comment]
No problem. Yeah I'm pretty sure it's just temporarily not working because of a Spotify update - seems like some stuff is currently broken.
https://github.com/khanhas/spicetify-cli/issues/1344

**Comment by theRealPadster** [comment]
@djpowers Is it still broken for you? I'm also running 1.1.74.631.g0b24d9ad on macOS (12.0.1) and I have the menu item.

**Comment by djpowers** [comment]
I just revisited this and the suggestion that was since posted in the spicetify issue you linked above (running `spicetify restore backup apply`) got things working for me. Thanks!

**Comment by mangkoran** [comment]
I got this issue too.
```
Spotify for Win32 1.1.76.447.g11f432d8
Spicetify 2.8.4
```

**Comment by theRealPadster** [comment]
> I got this issue too.
> 
> ```
> Spotify for Win32 1.1.76.447.g11f432d8
> Spicetify 2.8.4
> ```

You've got the custom app added to your custom apps folder and config file? 

Can you run `Spicetify.test() ` in the Spotify dev tools and send the results?

**Comment by mangkoran** [comment]
Sorry, what custom apps did you refer to? I don't have any custom apps in `CustomApps` directory.

Also how can I open dev tools?

**Comment by theRealPadster** [comment]
Oh, my bad, I meant the extensions folder and config. If you run `spicetify enable-devtool` it will allow you to right-click and inspect element in Spotify.

**Comment by mangkoran** [comment]
```
Spicetify.test()
spicetifyWrapper.js:156 25/25 Spicetify methods and objects are OK.
spicetifyWrapper.js:165 34/34 Spicetify.Player methods and objects are OK.
spicetifyWrapper.js:169 Spicetify method version exists but is not in the method list. Consider adding it.
spicetifyWrapper.js:169 Spicetify method expFeatureOverride exists but is not in the method list. Consider adding it.
spicetifyWrapper.js:175 Spicetify.Player method playUri exists but is not in the method list. Consider adding it.
```

**Comment by theRealPadster** [comment]
Weird, it's not saying that the APIs are missing. You've ran `spicetify apply` with the extension enabled?

**Comment by mangkoran** [comment]
Pretty sure I already have. I will try it again after I'm back home.

**Comment by theRealPadster** [comment]
@mangkoran ?

**Comment by mangkoran** [comment]
Sorry, the notification got buried. I tried `spicetify apply` again and the option still not there. Note that I also use https://github.com/mrpond/BlockTheSpot.

`.spicetify/Extensions`
![image](https://user-images.githubusercontent.com/57625126/152924829-f4b39f26-e9c2-4223-90c0-8051a4a37cfc.png)

`config-xpui.ini`
![image](https://user-images.githubusercontent.com/57625126/152924998-a12769a4-cdce-4c7e-9709-b5b0bacd146f.png)

![image](https://user-images.githubusercontent.com/57625126/152925286-182e77ce-eeff-4dc5-9d7d-f3e091dd9329.png)

**Comment by theRealPadster** [comment]
@mangkoran Your spicetify and Spotify are both outdated. Try updating them both and let me know if that helps. 
I have also just pushed an update (you'll need to re-download and replace `hidePodcasts.js`) that defaults to being enabled, which could serve as a workaround. 
@edmooredop Can you post what if gives you if you run `Spicetify.Menu.Item` in the developer console? 
You could also try the new version I just pushed up that enabled it by default.

**Comment by mangkoran** [comment]
I have updated both spicetify and Spotify.
```
Spotify for Win32 1.1.78.765.g5ea20b00
Spicetify v2.9.0
```
After downloading the latest `hidePoscasts.js` and force-enabling it, I can confirm that the podcasts suggestion is now gone!

Although, the button still not appeared..

![image](https://user-images.githubusercontent.com/57625126/153538319-de4d3f9c-4a52-4671-bccc-d5c91b7d9e4f.png)

**Comment by theRealPadster** [comment]
Awesome, glad it's working for you finally!
