### ISSUE TITLE
Podcasts tab still shows in 'Your Library'

### ISSUE THREAD

**Issue by GeorgeHahn** [theRealPadster/spicetify-hide-podcasts#24]
**Describe the bug**
One mention of podcasts remains in the 'Your Library' tabs

**To Reproduce**
Steps to reproduce the behaviour:
1. Click 'Your Library' in the sidebar
2. A 'Podcasts' tab is shown

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/502747/149462917-f0ad1f8b-1928-4269-b9b2-ef26fde74bf6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Spotify version: 1.1.76.447.g11f432d8
 - Spicetify version: 2.8.4
 - Extension version: be1d7b6

**Comment by sagars007** [comment]
Ahh the corresponding CSS class name for the tab changed to an obfuscated class name in the latest Spotify update. Thus the hidePodcasts extension is unable to hide it, as it is not able to point to it correctly. The current obfuscated class name for the element (`OEFWODerafYHGp09iLlA`) must be mapped to `queue-tabBar-header` in the Spicetify css-map. 
The change must be pushed upstream to the Spicetify-cli repo. I'll open a pull request there for the same. I hope it will get merged soon.

Until then, if needed, you can hide the Podcasts tab by changing `queue-tabBar-header` to `OEFWODerafYHGp09iLlA` in line 84 of `hidePodcasts.js`. This is a temporary fix until the css-map gets updated.

![Screenshot 2022-01-18 002906](https://user-images.githubusercontent.com/56472130/149835265-fce98f7c-07e2-4008-a2c7-6a736048d887.jpg)

@theRealPadster 
![Screenshot 2022-01-18 002410](https://user-images.githubusercontent.com/56472130/149835326-70e2b5ee-a8b3-47ab-b29a-20f3653bc824.jpg)
![Screenshot 2022-01-18 003318](https://user-images.githubusercontent.com/56472130/149835350-7c521bbb-7789-4ca1-8a97-fccb7133ee63.jpg)

**Comment by theRealPadster** [comment]
@sagars007 hey thanks so much for doing this! I've been pretty busy and haven't had a chance to look myself, but this looks perfect 👌

**Comment by sagars007** [comment]
Awesome! Really love the extension and I'm glad to help

**Comment by afonsojramos** [comment]
https://github.com/khanhas/spicetify-cli/pull/1414 has closed so maybe this can be closed too!

**Comment by theRealPadster** [comment]
Awesome, thanks @afonsojramos ! 
@GeorgeHahn you should be able to run `spicetify backup restore apply` to get it working now. Please reopen the issue if it's still not working.

**Comment by afonsojramos** [comment]
*`spicetify restore backup apply`
