### ISSUE TITLE
No 'hide podcasts' in menu

### ISSUE THREAD

**Issue by iholas** [theRealPadster/spicetify-hide-podcasts#26]
Hey. Installed the extension today and while I can modify my home screen, cannot just hide podcasts: 
I have attempted to reapply config and relaunch the client manually. No luck so far. 
![image](https://user-images.githubusercontent.com/22399272/154043459-0c3a439b-3490-461c-b2ce-6f34a6b9a38b.png)
![image](https://user-images.githubusercontent.com/22399272/154043605-1ca85bb4-c7cc-4119-af2c-43e3f92ff785.png)
![image](https://user-images.githubusercontent.com/22399272/154043697-6bfb9055-5c78-4648-bbac-677a2734b065.png)

**Comment by theRealPadster** [comment]
What Spotify and Spicetify version do you have? There was an update to Spicetify (2.9.1) yesterday. 
What version (commit) of the extension do you have?

**Comment by roccolord** [comment]
I have 2.9.0 of spicetify and Spotify for macOS (Apple Silicon) 1.1.79.763.gc2965cdf and the same issue.

**Comment by roccolord** [comment]
Did a:
`robert@rpro Extensions % spicetify upgrade
robert@rpro Extensions % spicetify restore backup apply`

and now it's back working again!

**Comment by theRealPadster** [comment]
Closing because it seems like a Spotify/Spicetify version related issue and not specific to the Hide Podcasts extension.
