### ISSUE TITLE
Sharing your custom app

### ISSUE THREAD

**Issue by 3raxton** [theRealPadster/spicetify-hide-podcasts#3]
Hey there,

I've seen your custom app for Spicetify and understand the struggle of getting them out to users. I've recently created a community based repo for developers of customs apps to share their apps.

If you're interested in creating a pull request to share your custom app with others who are searching for different custom apps for Spicetify, feel free!

Please don't feel required to create a pull request. However, I figured I'd share the repo with you since you've created a custom app, and you may be interested in getting it out to users.

https://github.com/3raxton/spicetify-customapps

Cheers!

**Comment by theRealPadster** [comment]
Hey, thank you for your interest! I do like the idea of having a central place where users can find Spicetify extensions, since I looked for one myself when I developed this one, and didn't find one. However, I'm not really a fan of the "Donate" paragraph, as it gives the impression that you are the main contributor for the apps listed in the repo, and directs any funds towards yourself. This is likely not your intent, and I would suggest updating the paragraph to clarify your role, and to include a list of the apps and links to their repos/websites, for proper attribution. I know that it is a very early stage project, and no other apps have been added yet, so there's not much to add or link there, but I could try writing something up quickly (which you are free to modify and contribute to) in my pull request, if you'd be open to this idea.

**Comment by 3raxton** [comment]
I totally understand that, and I'll remove it. It's a bit embarrassing because I make my repos by using template READMEs and repo layouts then replacing the common words within the README. Definitely not an intentional thing; my bad! 😅

Good idea for the attribution! Would you elaborate a bit more on that so I can understand what you're envisioning? 

Thanks again for making me aware of my mistakes! Changing the donate section (again, sorry) now!

**Comment by theRealPadster** [comment]
Haha all good, thank you 🙂 

I would add a section near the top of the readme somewhere that has something like a bulleted list of the apps included, and a link to their repo+author. 

e.g. 

## Attribution
This repository is a centralized collection of community-made custom apps/extensions for [Spicetify](https://linkhere.com). Thanks to these awesome people who make Spotify better for all of us!
* [spicetify-hide-podcasts](https://github.com/theRealPadster/spicetify-hide-podcasts/) by [theRealPadster](https://github.com/theRealPadster/)
* [custom-app-2](https://github.com/theRealPadster/spicetify-hide-podcasts/) by [someguy83](https://github.com/theRealPadster/)
* [some other app](https://github.com/theRealPadster/spicetify-hide-podcasts/) and [yet another app](https://github.com/theRealPadster/spicetify-hide-podcasts/) by [SomeoneElse](https://github.com/theRealPadster/)

---

The links would go to the relevant pages, of course, and that's just a rough idea not final copy or anything.

**Comment by 3raxton** [comment]
I think it's a solid idea, but I’m afraid of how long the README could become if many apps are added to the repo. This could be solved with a simple details tag or a second markdown file with a mention of it in the README. I’ve used a details tag before in a previous README, and it’s fairly overwhelming, so I’m hesitant.

Any thoughts on a second file for attributions with a mention in the README to prevent overwhelming readers?

**Comment by theRealPadster** [comment]
Ah, fair point. A separate attribution file would also work. I think each extension will probably also have its own readme in its folder regardless. What is a details tag?

**Comment by 3raxton** [comment]
I agree. I think something like an attribution.md file would be the way to go with a mention of it in the README.

As for the details tag, it’s the <details> HTML tag that allows for rolling down/up a section in HTML.

I’ll set up the attribution file soon unless you’d like to initiate it with a PR.

**Comment by theRealPadster** [comment]
Ah, I see. Yeah the details tag would make the markdown kinda messy. A mention in the readme with a link to the attribution.md would be fine. You can set it up if you'd like. It'll probably be a few days before I get around to my PR.

**Comment by 3raxton** [comment]
This week is going to be fairly packed for me but I’ll set it up. Feel free to watch so you can see when I add it.

Thanks again
