### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by francescoaracu** [theRealPadster/spicetify-hide-podcasts#34]
### What language are you adding?

Italiano (Italian)

### Menu title

Nascondi podcast

### Enabled

Attivato

### Aggressive mode

Modalità aggressiva

### Search page shelf label

Cosa vuoi ascoltare?

**Comment by theRealPadster** [comment]
Added, thank you! To use it:
- You can download the latest `hidePodcasts.js` from the main branch, replace your local copy, and `spicetify apply`
- Or if you're using Marketplace, you may need to wait up to 24h, and restart Spotify.
