### ISSUE TITLE
"Podcast New Releases" showing on Home page

### ISSUE THREAD

**Issue by justinlaselva** [theRealPadster/spicetify-hide-podcasts#43]
Howdy!

Thanks for this Spicetify extension—it's great!

I noticed after updating Spotify, Spicetify, and the spicetify-hide-podcasts extension that a "Podcast New Releases" section now shows up on my Spotify home screen. This is the only place I see podcasts in the Spotify client.

I'm using Spotify 1.1.96.785.g464c973a on macOS with Spicetify 2.14.0 and spicetify-hide-podcasts from 11 days ago, current as of commit c8f29b1.

Please let me know if you need any other information. Thanks!

**Comment by justinlaselva** [comment]
Actually, bummer, I have hidePodcasts.js in my `config-xpui.ini` file but it looks like it might not be having any effect after running `spicetify apply`. I am seeing "Shows you might like" and other podcasts, and there is no longer any option to Hide Podcasts under the account menu in the top right.

**Comment by theRealPadster** [comment]
Hey thanks, I've been meaning to take a look at any bugs once I got the new Spotify UI rolled out to my account. I have it now, so will take a look once I get the chance. I'm assuming you've got the new UI as well? With the big search bar top centre and the home button next to it.

**Comment by theRealPadster** [comment]
I noticed that on initial load, it wasn't detecting podcasts on the homepage. I've added logic to better detect when the homepage has loaded, and it seems to be working for me. 

Can you download the latest version (from 358945db793e8054fbb70805bf578dc01cb62be5) and try it again? I also added a console log so you can check if it's running by looking for "HidePodcasts: Loaded" in the devtools console.

**Comment by justinlaselva** [comment]
Actually, no, though I'm at the latest version of the Spotify client, my UI has remained the same!

I downloaded the latest version of hidePodcasts.js and applied it, and also upgraded to the latest version of Spicetify (2.14.1 as of today), but I think I probably have deeper issues than with your extension. Though Spicetify is definitely working (I can see the experimental features and configure the sidebar from the profile menu), enabling DevTools doesn't seem to have any effect in my client (Ctrl-Shift-I does nothing) and I'm still not seeing the option to hide podcasts in the profile menu even with the extension applied.

I'm now on Spotify 1.1.97.962.g24733a46 and I suspect this release is just too new for Spicetify to work properly. I don't want to pester you about your extension when I think my problems are probably beyond that.

Thanks for the update and the reply, though! I'm looking forward to getting this working again in my client once Spicetify catches up with the latest Spotify client release.

**Comment by justinlaselva** [comment]
Heh, just wanted to follow up, because I'm a dummy. As part of upgrading everything, I was cURLing the wrong address for the `hidePodcasts.js` file, and I was grabbing the HTML page:

- https://github.com/theRealPadster/spicetify-hide-podcasts/blob/main/hidePodcasts.js

rather than the raw JavaScript file:

- https://raw.githubusercontent.com/theRealPadster/spicetify-hide-podcasts/main/hidePodcasts.js

I replaced the file and everything is working as expected, again. You can mark this one as not a bug. :-)

**Comment by theRealPadster** [comment]
Ah haha perfect 😂
