### ISSUE TITLE
Podcast showing in Search page (new UI)

### ISSUE THREAD

**Issue by francescoaracu** [theRealPadster/spicetify-hide-podcasts#52]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.2.1.968.g21027577
Spicetify v2.15.0
```

### 📝 Description

When I click on the search bar, Podcasts card is showing, even with Aggressive mode enabled.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/48188510/208686421-a92f9c91-9f0c-4a0f-9b40-3fb5ceb13ff2.png)

**Comment by theRealPadster** [comment]
Can you run `spicetify enable-devtools` and open the Spotify dev tools to check the console for the following:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/1565883/208995200-0c0061c7-b25e-4c37-86bf-bfd7f3910883.png">
<img width="820" alt="image" src="https://user-images.githubusercontent.com/1565883/208995281-01965f07-2a37-44ac-b8ad-9d734040ab3c.png">

Or any other errors? It works fine for me on:
> Spotify for macOS (Apple Silicon)
> 1.2.0.1165.gabf054ab
> Spicetify v2.14.3

What version/release of the hide podcasts extension are you using?

**Comment by francescoaracu** [comment]
This is the console screenshot after running the command you told me.
![image](https://user-images.githubusercontent.com/48188510/209005892-33418222-8895-46df-bfbf-0f438246e0ca.png)

Anyway, the extension is on its latest version, 2.5.2 from Releases.

**Comment by theRealPadster** [comment]
I just enabled the experimental feature "enable the new home structure and navigation", which I believe is the "new UI", and tested it, and it still seems to block the podcasts item for me. 

> Spotify for macOS (Apple Silicon)
1.2.4.912.g949d5fd0
Spicetify v2.16.1
xpui_2023-01-31_1675173298148_949d5fd
cef_109.1.11+g6d4fdb2+chromium-109.0.5414.87

Is it still broken for you? 

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/1565883/219877096-8bf8c86d-a4e0-4796-9c8c-49adf2f95f82.png">

**Comment by theRealPadster** [comment]
@francescoaracu I've rewrote the search page podcast detection in the latest 2.8.0 release. Could you try it again?

**Comment by francescoaracu** [comment]
Hi man, I tried it now and it's hiding the Podcast tab in Search only in aggressive mode; I'm using Bloom theme.

**Comment by theRealPadster** [comment]
Okay, I'm gonna close the issue since it's hiding now. I'm not sure if the theme matters or not, but it might affect things depending if it does anything with a JS extension.
