### ISSUE TITLE
[Question/feature request] Hiding audiobooks

### ISSUE THREAD

**Issue by hotsno** [theRealPadster/spicetify-hide-podcasts#58]
I completely understand if this isn't within the scope of this extension but would you consider extending the functionality to block audiobooks as well?

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/71658949/211664761-971c76dc-32ef-4f6b-a0c0-5567c79f5253.png">

Also wondering if any extension like this already exists that I might be missing?

**Comment by theRealPadster** [comment]
Yeah I can look into adding an option for that. I'm not sure where I'd find audio books though; I've never seen any in my Spotify.

**Comment by hotsno** [comment]
That would be great if you end up getting it working!

I just recently got this section on my Spotify macOS app a couple days ago. I think the home page is different for everybody, so you might just have to get (un)lucky for it to show up there. You probably know more about that than I do.

What's weird is that nothing was showing up in this section even though (I think) I had no extension installed that should have been doing that. Though maybe I had some installed that weren't showing up in the `Marketplace`'s  installed section. Anyways, probably not relevant but just thought I'd share.

**Comment by theRealPadster** [comment]
@hotsno 
I still don't have them showing up for me, but I have an idea. If you run this on your homepage when the audio books are showing, I should be able to get what I need to hide the audio book carousels. 

```js
const shelves = document.querySelectorAll('.main-shelf-shelf');

const shelfInfo = [...shelves].reduce((acc, shelf) => {
  const title = shelf.getAttribute('aria-label') || 'no-aria-label';
  const cardLinks = [
    ...shelf.querySelectorAll('.main-cardHeader-link'),
  ];
  const links = cardLinks.map(link => ({
    title: link.getAttribute('title'),
    href: link.getAttribute('href'),
  }));
  acc.push({
    title,
    links,
  });
  return acc;
}, []);

console.log(shelfInfo);
```

To do this, run `spicetify enable-devtools`, then open the dev tools and go to `console`, paste it in, hit enter, and right-click to copy the output. 

<img width="862" alt="image" src="https://user-images.githubusercontent.com/1565883/220472203-b671cdd8-5a29-4e30-91af-ce3f37fe80f0.png">

**Comment by theRealPadster** [comment]
Someone on the Spicetify Discord had the same issue, and when they ran the above code, their audiobook cards had hrefs that started with `/show/`, like podcasts do, and they disappeared when installing this extension. So I'm wondering if it's resolved and podcasts and audiobooks both start with `/show/` now? Otherwise, using a snippet like this may do the trick, but it's less reliable, as it requires the shelf to have the word "audiobook" in the title, in lowercase. 

```css
.main-shelf-shelf[aria-label*="audiobook"] {
  display: none;
}
```

**Comment by theRealPadster** [comment]
I've added support with #74 
Please open another issue is still seeing audiobooks.
