### ISSUE TITLE
Carousels not hidden again

### ISSUE THREAD

**Issue by theRealPadster** [theRealPadster/spicetify-hide-podcasts#6]
Spotify updated and it looks like my class-based podcast carousel method is not working any more. The class is now `Card--playlist` instead of `Card--show`. I'll have to find another way of detecting them. 

![image](https://user-images.githubusercontent.com/1565883/105728830-933cc380-5efa-11eb-8565-7d04ab923d47.png)

This is a re-hash of #5

**Comment by theRealPadster** [comment]
Ideas: 

Potentially use a library (e.g. https://www.npmjs.com/package/spotify-url-info) to get info for the playlists or items in the carousels, and hide based on that. That would require making multiple requests for each carousel, and probably slow down the app a bit, at least when loading a new page. But I don't see another way of detecting podcasts now that they appear to show up as playlists.

**Comment by theRealPadster** [comment]
Oh, it looks like the ones in my screenshot are actually playlists of podcast episodes and content. Maybe I just need to add my other check back in, that checks if the word podcast appears in the title/description, since they are, in fact, playlists technically.

**Comment by huckenfard** [comment]
I love what you're doing this has been a real annoyance to me! Hope you fix this issue soon.

**Comment by theRealPadster** [comment]
@huckenfard  Thanks! I just put the old check back in place, so it should now match any `.Card--show` carousels, or if they have the word "Podcast" in the title or description. This fixed the "Podcasts and more" carousel in the "Made for you" section for me. Let me know if there are any other spots that you still see after updating :)
