### ISSUE TITLE
Does not work with the new Spotify display

### ISSUE THREAD

**Issue by Darkempire78** [theRealPadster/spicetify-hide-podcasts#8]
The extension does not work anymore with the new Spotify display

![image](https://user-images.githubusercontent.com/50015928/118715928-8420af00-b824-11eb-8e4e-67b85127f91c.png)

**Comment by theRealPadster** [comment]
Yep, I noticed this. Looks like they changed everything so I need to update the tagging method. And then the content doesn't seem to exist immediately after page load, so I need to figure out some way to delay the logic or detect when it's ready...

**Comment by theRealPadster** [comment]
@Darkempire78 I've started working on updating it. The lastest code in the [xpui branch](https://github.com/theRealPadster/spicetify-hide-podcasts/tree/xpui) hides the carousels on the homepage on initial app load. Feel free to test that out. V2 doesn't appear to be firing the "appchange" event when switching pages, so I'm gonna have to look into that before I can remove podcast stuff from the other pages.

**Comment by theRealPadster** [comment]
@Darkempire78 I've published the v2 version, which you can check out on its release page [here](https://github.com/theRealPadster/spicetify-hide-podcasts/releases/tag/v2.0.0). Could you give it a try when you have a chance?

**Comment by Darkempire78** [comment]
It seems to work well! @theRealPadster
