### ISSUE TITLE
Podcasts still showing up on homepage

### ISSUE THREAD

**Issue by ianrispin** [theRealPadster/spicetify-hide-podcasts#80]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.94.870.gf994cb0b
- Spicetify version: 2.20.1
- Theme: Comfy
- MacOS Monterey, version 12.5
```

### 📝 Description

Recently listened to podcasts still show up on the home page (screenshot below)

### 📸 Screenshots

<img width="1052" alt="image" src="https://github.com/theRealPadster/spicetify-hide-podcasts/assets/50210259/a2ee3a05-2cda-4bbc-886e-a13feabe70fa">

**Comment by theRealPadster** [comment]
Could you try updating your Spotify and spicetify? 1.1.94 is quite old.

**Comment by ianrispin** [comment]
That's the latest version for me.

**Comment by ianrispin** [comment]
Okay, I've updated, but they're still there

**Comment by theRealPadster** [comment]
@ianrispin Is this still an issue on the latest version?
@xoorath I updated the build system to fix an issue that may have been introduced last week with the Spicetify-Creator 1.0.16 release. Can you download the latest release (https://github.com/theRealPadster/spicetify-hide-podcasts/releases/tag/v.2.7.2) and see if it works now?

**Comment by ianrispin** [comment]
Technically, no. Podcasts aren't showing up on the homepage regardless of whether or not I have the extension enabled. That's not an issue for me personally, but it could be for someone else if they sometimes want podcasts to show up.

**Comment by theRealPadster** [comment]
> Technically, no. Podcasts aren't showing up on the homepage regardless of whether or not I have the extension enabled. That's not an issue for me personally, but it could be for someone else if they sometimes want podcasts to show up.

I don't really see how this helps? You just mean you personally aren't getting podcasts recommended to you? I want to know if the extension is working, which is meant to hide them. If someone has them recommended they should be able to toggle it with the extension...

**Comment by ianrispin** [comment]
Yeah, the podcast recommendations just don’t show up whether the extension is on or off. Not really sure whether this is caused by the extension refusing to unhide the podcasts or if it’s something unrelated to the extension. Sorry I couldn’t be of more help

**Comment by theRealPadster** [comment]
Okay thanks. The way the extension works is it detects and tags elements related to podcasts, and then hides them via CSS if you toggle it on. So if it's off, it won't do anything, same if Spotify just hasn't recommended any podcasts to you. 

I'm gonna close this issue since it should be fixed and nobody else has replied.

**Comment by xoorath** [comment]
> @ianrispin Is this still an issue on the latest version? @xoorath I updated the build system to fix an issue that may have been introduced last week with the Spicetify-Creator 1.0.16 release. Can you download the latest release (https://github.com/theRealPadster/spicetify-hide-podcasts/releases/tag/v.2.7.2) and see if it works now?

I think it does work for me, thank you.
