### ISSUE TITLE
Add possibility to remove "Your Episodes" from the new Playlists sidebar

### ISSUE THREAD

**Issue by symbion6** [theRealPadster/spicetify-hide-podcasts#86]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.14.1149
- Spicetify version: 2.20.3
```

### 📝 Description

The new library sidebar now lists "Liked Songs" and a "Your Episodes" playlist on the top of the playlist area.
"Your Episodes" is a playlist that contains a list of all saved Podcasts.
It stays visible even if the content is empty.
It cannot be removed natively.

Please add an option to remove this "Your Episodes" playlist.

For users that do not want to see anything podcast-related, it can be quite annoying to have to see this playlist everytime they're interacting with their playlists.

### 📸 Screenshots

https://imgur.com/a/lkdLof7

**Comment by theRealPadster** [comment]
I don't have a "your episodes" in my sidebar. Could you open the devtools (`spicetify enable devtools` and inspect the "your episodes" item and share a screenshot or a copy of the DOM? That might help me figure out how to detect it. 
<img width="1512" alt="image" src="https://github.com/theRealPadster/spicetify-hide-podcasts/assets/1565883/e2e0d446-34d3-4c86-83ef-5192ca41fcec">

**Comment by symbion6** [comment]
Here you go! Sorry for the delay. I thought it was a big hassle to get the devtools working but apparently, didn't read well!

[Screenshot 2024-01-12 at 13 08 21](https://github.com/theRealPadster/spicetify-hide-podcasts/assets/35668196/321670ce-a73f-4037-a380-2e53a23bc744)

**Comment by theRealPadster** [comment]
Alright, I used that as reference to find that spot in the DOM in my own Spotify, to hopefully detect it. Could you download the latest version of hidePodcasts.js (manual install, not marketplace) and see if it works? If it does, I'll do a new release. If not, you can repoen the issue and I can look again.

**Comment by symbion6** [comment]
Thanks a lot for the fix! Really appreciated.
